import { useState } from "react";
import { Alert, Pressable, SafeAreaView, StyleSheet, Text, TextInput, View } from "react-native";
import { signInWithEmailAndPassword, createUserWithEmailAndPassword } from "firebase/auth";
import { auth, isFirebaseConfigured } from "../lib/firebase";
const C={bg:"#F7F7FA",card:"#fff",text:"#17191F",muted:"#7B7F89",blue:"#2455D6",border:"#E8E9EE"};
export default function Login(){
 const [mode,setMode]=useState<"login"|"signup">("login"),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[busy,setBusy]=useState(false);
 const submit=async()=>{if(!email.trim()||password.length<6)return Alert.alert("Check details","Enter a valid email and a password of at least 6 characters.");if(!isFirebaseConfigured||!auth)return Alert.alert("Firebase not configured","Add the EXPO_PUBLIC_FIREBASE_* values from .env.example, then restart Expo.");try{setBusy(true);if(mode==="login")await signInWithEmailAndPassword(auth,email.trim(),password);else await createUserWithEmailAndPassword(auth,email.trim(),password)}catch(e:any){Alert.alert("Authentication failed",e?.message||"Please try again.")}finally{setBusy(false)}};
 return <SafeAreaView style={s.safe}><View style={s.card}><View style={s.logo}><Text style={s.logoText}>RP</Text></View><Text style={s.title}>{mode==="login"?"Welcome back":"Create account"}</Text><Text style={s.sub}>{mode==="login"?"Sign in to continue":"Create your account to continue"}</Text><Text style={s.label}>Email</Text><TextInput autoCapitalize="none" keyboardType="email-address" value={email} onChangeText={setEmail} placeholder="you@example.com" style={s.input}/><Text style={s.label}>Password</Text><TextInput secureTextEntry value={password} onChangeText={setPassword} placeholder="Minimum 6 characters" style={s.input}/><Pressable disabled={busy} style={s.button} onPress={submit}><Text style={s.buttonText}>{busy?"Please wait…":mode==="login"?"Sign in":"Create account"}</Text></Pressable><Pressable onPress={()=>setMode(mode==="login"?"signup":"login")}><Text style={s.switch}>{mode==="login"?"New here? Create an account":"Already have an account? Sign in"}</Text></Pressable>{!isFirebaseConfigured&&<Text style={s.demo}>Firebase is not configured. Add credentials before using accounts.</Text>}</View></SafeAreaView>
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:C.bg,justifyContent:"center",padding:20},card:{backgroundColor:C.card,borderRadius:22,padding:24,borderWidth:1,borderColor:C.border},logo:{width:62,height:62,borderRadius:31,backgroundColor:"#222C55",alignItems:"center",justifyContent:"center",alignSelf:"center",marginBottom:18},logoText:{color:"#fff",fontSize:20,fontWeight:"800"},title:{fontSize:28,fontWeight:"800",color:C.text,textAlign:"center"},sub:{fontSize:13,color:C.muted,textAlign:"center",marginTop:5,marginBottom:25},label:{fontSize:13,color:C.muted,marginBottom:7},input:{height:52,borderWidth:1,borderColor:C.border,borderRadius:13,paddingHorizontal:14,fontSize:15,color:C.text,marginBottom:16},button:{height:52,borderRadius:13,backgroundColor:C.blue,alignItems:"center",justifyContent:"center"},buttonText:{color:"#fff",fontWeight:"800",fontSize:15},switch:{color:C.blue,textAlign:"center",fontWeight:"700",marginTop:18},demo:{fontSize:11,color:C.muted,textAlign:"center",lineHeight:16,marginTop:18}});